name: Build wgrest
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          go get github.com/mitchellh/gox
          go get github.com/tcnksm/ghr
      - name: Run tests
        run: |
          go test ./... -count 1
      - name: Build
        run: |
          mkdir -p dist/
          gox -os="linux darwin" -arch="amd64" -output="dist/wgrest_{{.OS}}_{{.Arch}}" ./...